Unixon/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^cart/', include('cart.urls', namespace='cart')),
    re_path(r'^customer/', include('account.urls', namespace='account')),
    re_path(r'^account/', include('django.contrib.auth.urls')),
    re_path(r'^search/', include('haystack.urls')),
    re_path(r'^order/', include('orders.urls', namespace='orders')),
    re_path(r'^payment/', include('payment.urls', namespace='payment')),
    re_path(r'rosetta/', include('rosetta.urls')),
    re_path(r'^', include('catalog.urls', namespace='catalog')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import re_path
from . import views


app_name = 'account'


urlpatterns = [
    re_path(r'^$', views.dashboard, name='dashboard'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^edit/$', views.edit, name='edit'),
    re_path(r'^cancel/(?P<order_id>\d+)/$', views.cancel_order, name='cancel_order'),
    re_path(r'^clear/(?P<order_id>\d+)/$', views.clear_order, name='clear_order'),
]

cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

catalog/urls.py
from django.urls import re_path
from . import views
from .feeds import LatestProductsFeed

app_name = 'catalog'


urlpatterns = [
    re_path(r'^$', views.product_list, name='product_list'),
    re_path(r'^feed/$', LatestProductsFeed(), name='product_feed'),
    re_path(r'^help/$', views.help_center, name='help'),
    re_path(r'^careers/$', views.careers, name='careers'),
    re_path(r'^conditions/$', views.conditions, name='conditions'),
    re_path(r'^contact/us/$', views.contact, name='contact'),
    re_path(r'^delivery/$', views.delivery, name='delivery'),
    re_path(r'^secure/payment/$', views.secure_payment, name='payment'),
    re_path(r'^privacy/policy/$', views.privacy, name='privacy'),
    re_path(r'^responsibility/$', views.responsibility, name='responsibility'),
    re_path(r'^returns/$', views.returns_policy, name='returns'),
    re_path(r'^feedback/$', views.feedback, name='feedback'),
    re_path(r'^(?P<id>\d+)/$', views.product_review, name='product_review'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]

orders/urls.py
from django.urls import re_path
from . import views

app_name = 'orders'

urlpatterns = [
    re_path(r'^create/$', views.create_order, name='create_order'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 31)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, label_suffix=" ", label=_('Quantity'),
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                label=_('Update'),
                                initial=False,
                                label_suffix="",
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib import messages


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if cd['quantity'] > product.stock:
            messages.error(request, 'You have selected more than is available.The available stock is {}'.format(product.stock))
            return redirect('catalog:product_detail', product.id, product.slug)
        else:
            cart.add(product=product,
                     quantity=cd['quantity'],
                     update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Title {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet"  type="text/css" href="{% static 'catalog/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/style.css' %}">
</head>
<div class="container">
    <div class="header">
        <img class="logo" src="{% static 'catalog/img/unixon.png' %}">
    </div>
</div>

<!--navigation bar-->
<div class="container">
    <nav  class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'catalog:product_list' %}">UNIXON</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'catalog:product_list' %}">Home</a></li>
            <li><a href="/search/">
                <span class="glyphicon glyphicon-search"></span>
                Search
                </a>
            </li>
             <li><a href="{% url 'catalog:help'%}">Help Center</a> </li>
             {% if request.user.is_authenticated %}
            <li><a href="{% url 'account:dashboard' %}">My dashboard</a></li>
              {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="cart_price">
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    <a href="{% url 'cart:cart_detail' %}">
                        <span class="glyphicon glyphicon-shopping-cart"></span>
                        Your cart:
                       <span style="color:#0dcb2a;font-weight:normal;">{{ total_items }} item{{ total_items|pluralize }}, Ksh {{ cart.get_total_price }}</span>
                    </a>
                {% else %}
                     <a href="{% url 'cart:cart_detail' %}">
                        <span class="glyphicon glyphicon-shopping-cart"></span>
                        Your cart is empty
                     </a>
                {% endif %}
                {% endwith %}
            </li>
              {%if request.user.is_authenticated %}
              <li>
                  <a>
                      <span style="color:#2770cf">Hello {{request.user.username}},</span>
                  </a>
              </li>
               <li>
                    <a href="{% url 'logout' %}">
                      <span class="glyphicon glyphicon-log-out"></span>
                       Logout
                    </a>
               </li>
              {% else %}
                <li><a href="{% url 'account:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Log-in</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>
</div>
<body>

{% block body %}




{% endblock %}



    {% load static %}
<script src="{% static 'catalog/bootstrap/js/jquery.js' %}"></script>
<script src="{% static 'catalog/bootstrap/js/bootstrap.js' %}"></script>

</body>
</html>

cart/templates/cart/detail.html
{% extends 'catalog/base.html' %}

{% load static %}
{% block title %} Your shopping Cart {% endblock %}

{% block body %}
{% load i18n %}


<div class="container">
    <h1>{% trans 'Your shopping cart' %}</h1>
    <hr>
    <table class="cart">
        <thead>
            <tr>
                <th>{% trans 'Image' %}</th>
                <th>{% trans 'Product' %}</th>
                <th>{% trans 'Quantity' %}</th>
                <th>{% trans 'Remove' %}</th>
                <th>{% trans 'Unit price' %}</th>
                <th>{% trans 'Price' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="{% trans 'Update' %}">
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url 'cart:cart_remove' product.id %}">{% trans 'Remove' %}</a></td>
                <td class="num">Ksh {{ item.price }}</td>
                <td class="num">Ksh {{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">Ksh {{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'catalog:product_list' %}" class="button light">{% trans 'Continue shopping' %}</a>
        {% if cart|length < 1 %}
            <a href="{% url 'catalog:product_list' %}" class="button">{% trans 'Go home' %}</a>
        {% else %}
            <a href="{% url 'orders:create_order' %}" class="button">{% trans 'Checkout' %}</a>
        {% endif %}
    </p>
</div>

{%endblock %}