Unixon/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^cart/', include('cart.urls', namespace='cart')),
    re_path(r'^customer/', include('account.urls', namespace='account')),
    re_path(r'^account/', include('django.contrib.auth.urls')),
    re_path(r'^search/', include('haystack.urls')),
    re_path(r'^order/', include('orders.urls', namespace='orders')),
    re_path(r'^payment/', include('payment.urls', namespace='payment')),
    re_path(r'rosetta/', include('rosetta.urls')),
    re_path(r'^', include('catalog.urls', namespace='catalog')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

catalog/urls.py
from django.urls import re_path
from . import views
from .feeds import LatestProductsFeed

app_name = 'catalog'


urlpatterns = [
    re_path(r'^$', views.product_list, name='product_list'),
    re_path(r'^feed/$', LatestProductsFeed(), name='product_feed'),
    re_path(r'^help/$', views.help_center, name='help'),
    re_path(r'^careers/$', views.careers, name='careers'),
    re_path(r'^conditions/$', views.conditions, name='conditions'),
    re_path(r'^contact/us/$', views.contact, name='contact'),
    re_path(r'^delivery/$', views.delivery, name='delivery'),
    re_path(r'^secure/payment/$', views.secure_payment, name='payment'),
    re_path(r'^privacy/policy/$', views.privacy, name='privacy'),
    re_path(r'^responsibility/$', views.responsibility, name='responsibility'),
    re_path(r'^returns/$', views.returns_policy, name='returns'),
    re_path(r'^feedback/$', views.feedback, name='feedback'),
    re_path(r'^(?P<id>\d+)/$', views.product_review, name='product_review'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]

payment/urls.py
from django.urls import re_path
from . import views

app_name = 'payment'

urlpatterns = [
      re_path(r'^transact/$', views.payment_process, name='payment_process'),
      re_path(r'^top/up/$', views.credit_balance, name='credit_balance'),
      re_path(r'^activated/$', views.activate_account, name='activate_account'),
      re_path(r'^confirm/payment/(?P<id>\d+)/$', views.confirm_payment, name='confirm_payment')
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique_for_date='created')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    price = models.DecimalField(max_digits=6, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.IntegerField(default=30)
    description = models.TextField()

    class Meta:
        ordering = ('?',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product_detail', args=[self.id, self.slug])


class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Review by {} on {}'.format(self.user, self.product)


class Feedback(models.Model):
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Feedback by {}'.format(self.email)

payment/models.py
from django.db import models
from django.conf import settings


class Payment(models.Model):
    code = models.CharField(max_length=50, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    active = models.BooleanField()

    def __str__(self):
        return self.code


class Balance(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(auto_now_add=True)
    credit_number = models.IntegerField()
    amount = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    security_code = models.IntegerField(null=True)

catalog/forms.py
from django import forms
from .models import Review, Feedback
from django.utils.translation import gettext_lazy as _


class ReviewForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), label_suffix="", label=_('review'))

    class Meta:
        model = Review
        fields = ('body',)


class FeedbackForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}), label=_('Email'), label_suffix="")
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), label_suffix="", label=_('Body'))

    class Meta:
        model = Feedback
        fields = ('email', 'body')

payment/forms.py
from django import forms
from .models import Balance
from django.utils.translation import gettext_lazy as _


class PaymentForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label_suffix="")


class BalanceForm(forms.ModelForm):
    credit_number = forms.IntegerField(label=_('Credit card number'), widget=forms.NumberInput(attrs={'class': 'form-control'}), label_suffix="")
    amount = forms.DecimalField(label=_('Amount'), widget=forms.NumberInput(attrs={'class': 'form-control'}), label_suffix="")
    security_code = forms.IntegerField(label=_('Security code'),
                                       widget=forms.NumberInput(attrs={'class': 'form-control'}), label_suffix="")

    class Meta:
        model = Balance
        fields = ('credit_number', 'amount', 'security_code',)


class EditBalanceForm(forms.ModelForm):
    credit_number = forms.IntegerField(label=_('Credit card number'),
                                       widget=forms.NumberInput(attrs={'class': 'form-control'}), label_suffix="")
    amount = forms.DecimalField(label=_('Amount'), widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                label_suffix="")
    security_code = forms.IntegerField(label=_('Security code'),
                                       widget=forms.NumberInput(attrs={'class': 'form-control'}), label_suffix="")

    class Meta:
        model = Balance
        fields = ('credit_number', 'amount', 'security_code')

catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category, Review
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .forms import ReviewForm, FeedbackForm
from django.contrib import messages
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required


def product_list(request, category_slug=None):
    category = None
    shirt_cat = Category.objects.get(name='Shirts')
    trousers = Category.objects.get(name='Men trousers')
    women_trousers = Category.objects.get(name='Women trousers')
    women_suit = Category.objects.get(name='Women suit')
    blouse = Category.objects.get(name='Blouses')
    dress = Category.objects.get(name='Dresses')
    men_suit = Category.objects.get(name='Men suit')
    sweater = Category.objects.get(name='Sweaters')
    others = Category.objects.get(name='Others')
    shoes = Category.objects.get(name='Shoes')
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 12)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request, 'catalog/list.html', {'category': category,
                                                 'categories': categories,
                                                 'page': page,
                                                 'products': products,
                                                 'shirt': shirt_cat,
                                                 'trousers': trousers,
                                                 'women_trousers': women_trousers,
                                                 'women_suit': women_suit,
                                                 'blouse': blouse,
                                                 'dress': dress,
                                                 'men_suit': men_suit,
                                                 'sweater': sweater,
                                                 'shoes': shoes,
                                                 'others': others,
                                                 })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    reviews = product.reviews.filter(active=True)

    review_count = product.reviews.count()

    paginator = Paginator(reviews, 3)
    page = request.GET.get('page')
    try:
        reviews = paginator.page(page)
    except PageNotAnInteger:
        reviews = paginator.page(1)
    except EmptyPage:
        reviews = paginator.page(paginator.num_pages)

    cart_product_form = CartAddProductForm()
    return render(request,
                  'catalog/detail.html',
                  {'product': product,
                   'reviews': reviews,
                   'review_count': review_count,
                   'cart_product_form': cart_product_form})


@login_required
def product_review(request, id):
    product = get_object_or_404(Product, id=id, available=True)
    reviews = product.reviews.filter(active=True)

    if request.method == 'POST':
        review_form = ReviewForm(data=request.POST)

        if review_form.is_valid():
            new_review_form = review_form.save(commit=False)
            new_review_form.product = product
            new_review_form.user = request.user
            new_review_form.save()
            messages.success(request, 'Your review has successfully been submitted')
    else:
        review_form = ReviewForm()

    review_count = product.reviews.count()

    cart_product_form = CartAddProductForm()

    return render(request,
                  'catalog/review.html',
                  {'product': product,
                   'reviews': reviews,
                   'review_form': review_form,
                   'review_count': review_count,
                   'cart_product_form': cart_product_form})


def help_center(request):
    return render(request, 'catalog/help.html')


def returns_policy(request):
    return render(request, 'catalog/returns.html')


def secure_payment(request):
    return render(request, 'catalog/payment.html')


def responsibility(request):
    return render(request, 'catalog/responsibility.html')


def privacy(request):
    return render(request, 'catalog/privacy.html')


def delivery(request):
    return render(request, 'catalog/delivery.html')


def careers(request):
    return render(request, 'catalog/career.html')


def conditions(request):
    return render(request, 'catalog/conditions.html')


def contact(request):
    return render(request, 'catalog/contact.html')


def feedback(request):
    if request.method == 'POST':
        feedback_form = FeedbackForm(data=request.POST)
        if feedback_form.is_valid():
            feedback_form.save()
            messages.success(request, 'Thank you! Your feedback has successfully been received')
    else:
        feedback_form = FeedbackForm()
    return render(request, 'catalog/feedback.html', {'feedback_form': feedback_form})

payment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Payment, Balance
from orders.models import OrderDetails, Order
from .forms import PaymentForm, BalanceForm, EditBalanceForm
from decimal import Decimal


@login_required
def payment_process(request):
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']

            try:
                payment = Payment.objects.get(code__iexact=code, active=True)
                if payment:
                    payment.active = False
                    payment.user = request.user
                    payment.save()
                    return render(request, 'payment/payment_done.html')
            except:
                messages.error(request, "Error! please make sure you enter the correct transaction code then try again")

    else:
        form = PaymentForm()
    return render(request, 'payment/payment.html', {'form': form})


@login_required
def credit_balance(request):
    bal = get_object_or_404(Balance, user=request.user)
    if request.method == 'POST':
        bal_form = BalanceForm(data=request.POST or None)
        if bal_form.is_valid():
            cd = bal_form.cleaned_data
            bal.amount += cd['amount']
            bal.credit_number = cd['credit_number']
            bal.save()
            bal_form.save()
            messages.success(request, 'Your top up was successful')
        else:
            messages.error(request, 'Top up failed!')
    else:
        bal_form = BalanceForm(instance=request.user)
    return render(request, 'payment/credit.html', {'bal_form': bal_form})


@login_required
def activate_account(request):
    if request.method == 'POST':
        form = EditBalanceForm(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Your account has successfully been activated')
        else:
            messages.error(request, 'Top up failed!')
    else:
        form = EditBalanceForm()
    return render(request, 'payment/activated.html', {'form': form})


@login_required
def confirm_payment(request, id):
    user_balance = get_object_or_404(Balance, user=request.user)
    current_order = get_object_or_404(OrderDetails, id=id)
    ordered_items = Order.objects.filter(user=request.user)
    balance = user_balance.amount
    total_cost = current_order.get_total_cost()

    if balance >= Decimal(total_cost):
        user_balance.amount = balance - total_cost
        current_order.paid = True
        current_order.save()
        user_balance.save()
        for order in ordered_items:
            order.product.stock = order.product.stock - order.quantity
            order.product.save()
            order.save()
        return render(request, 'payment/payment_done.html')

    else:
        messages.error(request, 'Insufficient funds! Please top up your account then try again')
    return render(request, 'payment/pay.html', {'current_order': current_order})

catalog/templates/catalog/conditions.html
{% extends "catalog/base.html" %}

{% block title %}Terms and conditions{% endblock %}

{% block body %}
<div class="container">
    {% load i18n %}
    <h1>{% trans 'Terms and conditions' %}</h1>
    <hr>
    <p>1. Ordered goods will be approved upon six hours of placement of order.Otherwise will be cancelled.</p>
    <p>2. Approved orders will be cancelled if not paid within three days of approval.</p>
    <p>3. Paid goods will be delivered within three working days after payment.</p>
    <p>4. An order will only be considered paid if the customer pays the full amount required.</p>
    <p>5. Once an order has been paid, it cannot be cancelled.</p>
</div>
{% endblock %}

catalog/templates/catalog/contact.html
{% extends "catalog/base.html" %}

{% block title %}Contact us{% endblock %}

{% block body %}
<div class="container">
    {% load i18n %}
    <h1>{% trans 'Contact us' %}</h1>
    <hr>
    <P class="para">You can contact us using the following means:</P>
    <ul>
        <li>Email: unixon@gmail.com</li>
        <li>Tel: 0734344344</li>
    </ul>
</div>
{% endblock %}

catalog/templates/catalog/delivery.html
{% extends "catalog/base.html" %}

{% block title %}Delivery{% endblock %}

{% block body %}
<div class="container">
    {% load i18n %}
    <h1>{% trans 'Delivery' %}</h1>
    <hr>
    <p class="para">Goods ordered will be delivered 3 days after payment to the address specified<br>
        by the user during placement of order. The customer can pick the item any day once it is delivered </p>
</div>
{% endblock %}

catalog/templates/catalog/detail.html
{% extends 'catalog/base.html' %}

{% load static %}

{% block title %}
{% if category %} {{category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block body %}
{% load i18n %}

{% if messages %}
    {% for message in messages %}
        <div class="container">
            <div class="panel panel-default panther col-md-12">
                <div class="panel-body pan-bod">
                    <h2 class="message">{{ message|safe }} </h2>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}

<div class="container">
     <div class="panel panel-default col-md-5">
         <div class="panel-body img">
             <img src="{{product.image.url}}" class="img-responsive">
         </div>
    </div>
    <div class="col-md-5">
        <h1 class="detail">{{product.name}}</h1>
        <h2><a class="detail" href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="detail" id="money">Ksh {{product.price}}</p>
        {% if product.stock > 0 %}
        <p style="color:#6890a5"><strong>{% trans 'Available stock' %}: {{product.stock}}</strong></p>
        {% else %}
        <p style="color:#6890a5"><strong>{% trans 'Available stock: depleted '%}</strong></p>
        {% endif %}
          {{product.description|linebreaks}}
        {% if product.stock > 0 %}
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" id="tocart" value="{% trans 'Add to cart' %}">
            </form>
        {% endif %}
    </div>
    <a style="margin-top:35px;" href="{% url 'catalog:product_review' product.id%}" class="btn btn-success" role="button"><span class="glyphicon glyphicon-pencil"></span> <strong>{% trans 'Write a Review' %}</strong></a>
</div>
<div class="container">
    <h2 class="col-md-offset-1" id="prev_num">
        <span class="glyphicon glyphicon-thumbs-up"></span>
        <span class="glyphicon glyphicon-thumbs-down"></span>&nbsp;
        {{ review_count }} Review{{ review_count|pluralize }}
    </h2>
    {% for review in reviews %}
    <div class="review">
       <p class="info">
           {{review.user}}
       </p>
       <p>
           {{review.body|linebreaks}}
       </p>
       <p class="date">
           {{review.created}}
       </p>
    </div>
    <hr>
    {% empty %}
    <p class="date col-md-offset-1">{% trans 'There are no reviews for this product yet' %} </p>
    {% endfor %}
</div>

{% include 'catalog/pagination.html' with page=reviews %}
<div class="container">
</div>



{%endblock%}

catalog/templates/catalog/feedback.html
{% extends 'catalog/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}
{% if category %} {{category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block body %}
{% load i18n %}
{% if messages %}
    {% for message in messages %}
        <div class="container">
            <div class="panel panel-default panelia col-md-12">
                <div class="panel-body pan-bod">
                    <h2 class="message">{{ message|safe }} </h2>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}
<div class="container">
    <h1>{% trans 'Leave a feedback' %}</h1>
    <hr>
</div>
<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                <form action="." class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token%}
                    {% include 'catalog/form_template1.html'%}
                    <input type="hidden" name="next" value="{{ next }}" />
                    <div class="form-group">
                        <div class="col-sm-10">
                            <button type="Submit" class="btn btn-primary">{% trans 'Send Feedback' %}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{%endblock%}

catalog/templates/catalog/form_template.html
{% for field in review_form %}
    <div class="form-group">
        <div>
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <div class="col-md-12">
            <label class="control-label">{{field.label_tag}}</label>
        </div>
        <div class="col-md-6">
            {{field}}
        </div>
    </div>
{%endfor%}

catalog/templates/catalog/form_template1.html
{% for field in feedback_form %}
    <div class="form-group">
        <div>
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <div class="col-md-12">
            <label class="control-label">{{field.label_tag}}</label>
        </div>
        <div class="col-md-6">
            {{field}}
        </div>
    </div>
{%endfor%}

catalog/templates/catalog/help.html
{% extends 'catalog/base.html' %}

{% block title %} Help {% endblock %}

{% block body %}
{% load static %}
{% load i18n %}
    <div class="container">
        <h2>{% trans 'How to place an order' %}</h2>
        <hr>
        <p class="para">1. {% trans 'Navigate through the products and select the  products you want to purchase by clicking on the product' %}</p>
        <br>
        <img src="{% static 'catalog/img/image1.PNG' %}" class="img-responsive">
        <br>
        <p class="para">2. {% trans 'Click on the product you want to purchase the add it to the cart' %}</p>
        <br>
        <img src="{% static 'catalog/img/image2.PNG' %}" class="img-responsive">
        <br>
        <p class="para">3. {% trans 'Once you have exhausted your cart, click the checkout button and proceed to placing an order' %}</p>
        <br>
        <img src="{% static 'catalog/img/image3.PNG' %}" class="img-responsive">

    </div>

{% endblock %}

catalog/templates/catalog/most_purchased.html
<ul style="list-style-type:circle">
    {% for product in most_purchased %}
       <li><a class="list" style="text-decoration:none;outline:none;" href="{{product.product.get_absolute_url }}">{{product.product}}</a> </li>
    {% endfor %}
</ul>

catalog/templates/catalog/most_reviewed.html
<ul style="list-style-type:circle">
    {% for product in most_reviewed %}
       <li><a class="list" style="text-decoration:none;outline:none;" href="{{product.get_absolute_url }}">{{product.name}}</a> </li>
    {% endfor %}
</ul>

catalog/templates/catalog/pagination.html
        {% load static %}
        {% load i18n %}
    <link rel="stylesheet"  type="text/css" href="{% static 'catalog/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/style.css' %}">


<div class="container">
    <div class="det">
        <span class="step-links">
            {% if page.has_previous %}
                <a href="?page={{ page.previous_page_number }}">{% trans 'Previous' %}</a>
            {% endif %}

            <span class="current">
                {% trans 'Page' %} {{ page.number }} {% trans 'of' %} {{ page.paginator.num_pages }}.
            </span>

            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}">{% trans 'Next' %}</a>
            {% endif %}
        </span>
    </div>
</div>

catalog/templates/catalog/privacy.html
{% extends "catalog/base.html" %}

{% block title %}Privacy Policy{% endblock %}

{% block body %}
<div class="container">
    {% load i18n %}
    <h1>{% trans 'Privacy policy' %}</h1>
    <hr>
    <p class="para">Our customers are guaranteed of privacy in terms of personal information and any<br>
        other activities the customer is involved with while using our system.</p>
</div>
{% endblock %}

catalog/templates/catalog/responsibility.html
{% extends "catalog/base.html" %}

{% block title %}Responsibility{% endblock %}

{% block body %}
<div class="container">
    {% load i18n %}
    <h1>{% trans 'Responsibility' %}</h1>
    <hr>
    <p class="para">Unixon is responsible to ensuring better services to our customers and<br>
        better user experience with our system.</p>

</div>
{% endblock %}

catalog/templates/catalog/review.html
{% extends 'catalog/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}
{% if category %} {{category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block body %}

{% if messages %}
    {% for message in messages %}
        <div class="container">
            <div class="panel panel-default panelia col-md-12">
                <div class="panel-body pan-bod">
                    <h2 class="message">{{ message|safe }} </h2>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}

<div class="container">
    <h2>{% trans 'Review this product' %}</h2>
    <hr>
     <div class="panel panel-default col-md-5">
         <div class="panel-body img">
             <img src="{{product.image.url}}" class="img-responsive">
         </div>
    </div>
    <div class="col-md-5">
        <h1 class="detail">{{product.name}}</h1>
        <h2><a class="detail" href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="detail" id="money">Ksh {{product.price}}</p>
         {% if product.stock > 0 %}
        <p style="color:#6890a5"><strong>Available stock: {{product.stock}}</strong></p>
        {% else %}
        <p style="color:#6890a5"><strong>Available stock: depleted</strong></p>
        {% endif %}
          {{product.description|linebreaks}}
        {% if product.stock > 0 %}
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" id="tocart" value="{% trans 'Add to cart' %}">
            </form>
        {% endif %}
    </div>
    <a  style="margin-top:35px" href="{{ product.get_absolute_url }}" class="btn btn-success" role="button"><span class="glyphicon glyphicon-arrow-left"></span> {% trans 'Go back' %}</a>
</div>
<div class="container">
    <h2 class="col-md-offset-2" id="prev_num">
        <span class="glyphicon glyphicon-thumbs-up"></span>
        <span class="glyphicon glyphicon-thumbs-down"></span>
        &nbsp;
        {{ review_count }} Review{{ review_count|pluralize }}
    </h2>
</div>
<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                <form action="." class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token%}
                    {% include 'catalog/form_template.html'%}
                    <input type="hidden" name="next" value="{{ next }}" />
                    <div class="form-group">
                        <div class="col-sm-10">
                            <button type="Submit" class="btn btn-primary">{% trans 'Add a review' %}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{%endblock%}